import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import zka from "../public/zka.png";
import usayit from "../public/usayit.png";
import wordle from "../public/wordle.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Azka Azharan Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zka-icon.png" />
      </Head>

      <main className="bg-white px-7 sm:px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="px-4 sm:px-0 py-10 mb-2 sm:mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl select-none">zkaa</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 select-none"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5 sm:p-10 pt-0 pb-10 sm:pt-10">
            <h2 className="text-4xl sm:text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl select-none">
              Azka Azharan
            </h2>
            <h3 className="text-lg py-1 sm:text-2xl sm:py-2 dark:text-white md:text-3xl">
              Student and Developer
            </h3>
            <p className="text-xs sm:text-base py-3 sm:py-5 leading-5 sm:leading-8 text-gray-800 dark:text-gray-200 max-w-3xl mx-auto md:text-xl">
              As a college student pursuing a degree in software engineering, i
              am constantly seeking new opportunities to learn and grow. I am
              passionate about using my skills and knowledge to create
              innovative solutions and make a positive impact in the world. I am
              a quick learner and always eager to take on new challenges. In my
              free time, I enjoy staying up-to-date with the latest technologies
              and exploring new ways to apply my skills. I am excited to see
              what the future holds and am confident that my passion for
              software engineering will guide me towards a rewarding career.
            </p>
            <div className="text-3xl sm:text-5xl flex justify-center gap-8 sm:gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/zkazharan" target="_blank">
                <AiFillGithub />
              </a>
              <a
                href="https://linkedin.com/in/azka-ahmad-azharan"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://instagram.com/zkazharan" target="_blank">
                <AiFillInstagram />
              </a>
            </div>
            <div className="select-none relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 sm:w-72 sm:h-72 mt-10 sm:mt-20 overflow-hidden md:w-86 md:h-86">
              <Image
                src={zka}
                fill
                className="object-cover"
                draggable="false"
              />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-xl sm:text-3xl py-1 dark:text-white">
              Portofolio
            </h3>
            <p className="text-xs sm:text-base py-2 leading-5 sm:leading-8 text-gray-800 dark:text-gray-200">
              Highlighting my skills and achievements through a selection of my
              best work
            </p>
          </div>
          <div className="flex flex-col py-5 sm:py-10 justify-around lg:flex-row lg:flex-wrap">
            <div className="basis-5/12 relative select-none">
              <div className="absolute w-full h-full bg-gray-800/0 hover:bg-gray-800/90 rounded-lg ease-in duration-200 p-1">
                <a href="https://usayit.otech.id" target="_blank">
                  <div className="w-full h-full opacity-0 hover:opacity-100 p-10">
                    <p className="text-center w-full h-full text-gray-200 flex justify-center items-center text-xs sm:text-base md:text-xl lg:text-xs xl:text-sm font-medium">
                      Welcome to uSayIt, your go-to platform for anonymous
                      self-expression. As the lead front-end developer for this
                      project, I am proud to present a platform that allows you
                      to share your thoughts and feelings freely, without fear
                      of judgement. With just a few clicks, your words will be
                      shared on various social media outlets. So go ahead and
                      let your voice be heard - uSayIt is here to provide the
                      space and the freedom to do just that.
                    </p>
                  </div>
                </a>
              </div>
              <Image
                src={usayit}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                responsive
              />
            </div>
            <div className="basis-5/12 relative select-none mt-10">
              <div className="absolute w-full h-full bg-gray-800/0 hover:bg-gray-800/90 rounded-lg ease-in duration-200">
                <a href="https://wordle.otech.id" target="_blank">
                  <div className="w-full h-full opacity-0 hover:opacity-100 p-10">
                    <p className="text-center w-full h-full text-gray-200 flex justify-center items-center text-xs sm:text-base md:text-xl lg:text-xs xl:text-sm font-medium">
                      Wordle is a word guessing game that I developed using
                      Next.js and Tailwind CSS. Players must correctly identify
                      the letters in a hidden word. The project allowed me to
                      showcase my front-end development skills and create an
                      engaging and visually appealing game.
                    </p>
                  </div>
                </a>
              </div>
              <Image
                src={wordle}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                responsive
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
