import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import zka from "../public/zka.png";
import usayit from "../public/usayit.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Azka Azharan Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zka-icon.png" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl select-none">zkaa</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 select-none"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Azka Azharan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student and Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-3xl mx-auto md:text-xl">
              As a college student pursuing a degree in software engineering, i
              am constantly seeking new opportunities to learn and grow. I am
              passionate about using my skills and knowledge to create
              innovative solutions and make a positive impact in the world. I am
              a quick learner and always eager to take on new challenges. In my
              free time, I enjoy staying up-to-date with the latest technologies
              and exploring new ways to apply my skills. I am excited to see
              what the future holds and am confident that my passion for
              software engineering will guide me towards a rewarding career.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/zkazharan" target="_blank">
                <AiFillGithub />
              </a>
              <a
                href="https://linkedin.com/in/azka-ahmad-azharan"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://instagram.com/zkazharan" target="_blank">
                <AiFillInstagram />
              </a>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 mt-20 overflow-hidden md:w-86 md:h-86">
              <Image src={zka} fill className="object-cover" />
            </div>
          </div>
        </section>

        {/* <section>
          <div>
            <h3 className="text-3xl py-1">Lorem ipsum</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi
              quae voluptatem voluptates? Dicta sunt atque eligendi repellat
              suscipit repudiandae quas cum veritatis, laudantium numquam
              tempora nobis nemo exercitationem ratione fugit. Explicabo
              voluptate voluptatibus commodi ut placeat molestiae possimus
              laudantium, quaerat sequi, vitae voluptatem eaque voluptatum esse!
              Molestiae, dolorum magni, quisquam excepturi quo quibusdam vel
              odio debitis consectetur facilis eaque id?
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">Title</h3>
              <p className="py-2">
                desc descd escdescdes cdescd es cdesc d esc desc descd escdes
                cdesc descd escd escd escd esc desc
              </p>
              <h4 className="py-4 text-teal-600">Sub Title</h4>
              <p className="text-gray-800 py-1">point 1</p>
              <p className="text-gray-800 py-1">point 2</p>
              <p className="text-gray-800 py-1">point 3</p>
            </div>
          </div>
        </section> */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Highlighting my skills and achievements through a selection of my
              best work
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/2 relative">
              <div className="absolute w-full h-full bg-gray-800/0 hover:bg-gray-800/90 rounded-lg ease-in duration-200">
                <a href="https://usayit.otech.id" target="_blank">
                  <div className="w-full h-full opacity-0 hover:opacity-100 p-10">
                    <p className="text-center w-full h-full text-gray-200 flex justify-center items-center font-medium">
                      Welcome to uSayIt, your go-to platform for anonymous
                      self-expression. As the lead front-end developer for this
                      project, I am proud to present a platform that allows you
                      to share your thoughts and feelings freely, without fear
                      of judgement. With just a few clicks, your words will be
                      shared on various social media outlets, giving you the
                      opportunity to connect with others and express yourself
                      authentically. So go ahead and let your voice be heard -
                      uSayIt is here to provide the space and the freedom to do
                      just that.
                    </p>
                  </div>
                </a>
              </div>
              <Image
                src={usayit}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                responsive
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
